# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b5f8fe8f86112e3e918dc6855acf301ca0c81d69a2ad0aca0decc9be94deb9df1543c693558cfdea5f8699c4cf2eda3b58df2e8732c6717bc43625fe8af3e46c

test:
  secret_key_base: 4e49b7e1cda560964f0d33d9f9ff6c8cb11f87566ae2e98ef801cf8b0d8c4cceb4f7385e7a3789e25e9664f03e56fa549d4c178c66ca4629d08bcd68a90a5f9d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
